config/routes.rb
RailsFreshman::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :articles
  resources :links
  root to: "welcome#index"
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
end

app/models/setting.rb
# -*- encoding : utf-8 -*-
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  has_many :links
  
  extend OmniauthCallbacks

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def login_required
  	if current_user.blank?
  	  flash[:notice] = "Please Log In to Proceed."
  	  redirect_to new_user_session_path		
  	end  	
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, 
      :password, :password_confirmation)}
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		
	end
end

app/controllers/links_controller.rb
require 'uri'
class LinksController < ApplicationController

  before_action :login_required, only: [:new, :create]

  def index
    
    case params[:tag]
      when 'gem'
        @links = Link.where("tag=?", "Gem").order('created_at desc')
      when 'news' 
        @links = Link.where("tag=?", "News").order('created_at desc') 
      when 'teach'
        @links = Link.where("tag=?", "Teaching").order('created_at desc') 
      when 'discuss'
        @links = Link.where("tag=?", "Discussion").order('created_at desc')
      else
        @links = Link.all.order('created_at desc')
    end    
  	
  end

  def new
  	@link = Link.new
  end

  def create
  	
    @link = Link.new(url: params[:link][:url], tag: params[:link][:tag], 
      title: URI.decode(params[:title]), content: URI.decode(params[:description]), 
      thumbnail: URI.decode(params[:thumbnail_url]))

  	if @link.save
  	  redirect_to links_path
  	else
  	  render :index
  	end

  end


  private

  def link_params()
  	params.require(:link).permit(:url, :tag, :title, :content, :thumbnail)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/links_helper.rb
module LinksHelper
	
  def is_active(controller)
    params[:controller] == controller ? "active" : nil
  end

  def tag_setting(tag)
  	case tag
  	when "Gem"
  	  "label-primary"
  	when "News"
  	  "label-danger"
  	when "Teaching"
  	  "label-success"
  	when "Discussion"
  	  "label-warning"	
  	end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<div class="container">
  <div class="row row-offcanvas row-offcanvas-right">
    <div class="col-xs-12 col-sm-9">
      <div class="row">
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <img data-src="holder.js/300x200" alt="...">
            <div class="caption">
              <h3>Title</h3>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. </p>
              <p><a href="#" class="btn btn-primary" role="button">更多</a> <a href="#" class="btn btn-default" role="button">分享</a></p>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <img data-src="holder.js/300x200" alt="...">
            <div class="caption">
              <h3>Title</h3>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. </p>
              <p><a href="#" class="btn btn-primary" role="button">更多</a> <a href="#" class="btn btn-default" role="button">分享</a></p>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <img data-src="holder.js/300x200" alt="...">
            <div class="caption">
              <h3>Title</h3>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. </p>
              <p><a href="#" class="btn btn-primary" role="button">更多</a> <a href="#" class="btn btn-default" role="button">分享</a></p>
            </div>
          </div>
        </div>
      </div><!--/row-->
    </div><!--/span-->

    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
      <button type="button" class="btn btn-primary">新增</button>
      <hr>
      <div class="list-group">
        <a href="#" class="list-group-item active">Gem</a>
        <a href="#" class="list-group-item">新聞</a>
        <a href="#" class="list-group-item">教學</a>
        <a href="#" class="list-group-item">討論</a>
      </div>
    </div><!--/span-->
  </div><!--/row-->
  
  <div class="text-center">
    <ul class="pagination center">
      <li>
        <a href="#">prev</a>
      </li>
      <li>
        <a href="#">1</a>
      </li>
      <li>
        <a href="#">2</a>
      </li>
      <li>
        <a href="#">3</a>
      </li>
      <li>
        <a href="#">4</a>
      </li>
      <li>
        <a href="#">5</a>
      </li>
      <li>
        <a href="#">next</a>
      </li>
    </ul>
  </div>
</div><!--/.container-->

app/views/layouts/_footer.html.erb
<div id="footer">
  <p>&copy; Rails Freshman 2014</p>
</div>

app/views/layouts/_includes.html.erb
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" %>
<%= javascript_include_tag "http://cdn.embed.ly/jquery.embedly-3.0.5.min.js" %>
<%= javascript_include_tag "http://cdn.embed.ly/jquery.preview-0.3.2.min.js" %>
<%= javascript_include_tag "http://imagesloaded.desandro.com/imagesloaded.pkgd.min.js" %>
<%= javascript_include_tag "masonry.pkgd.min.js" %>
<%= stylesheet_link_tag("http://cdn.embed.ly/jquery.preview-0.3.2.css") %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Rails Freshman', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_right_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li> <%= link_to 'Articles', articles_path %> </li>
<li> <%= link_to 'Links', links_path %> </li>

app/views/layouts/_navigation_right_links.html.erb
<li> <%= link_to 'Log In', new_user_session_path %> </li>
<li class="navtext"> or Log In with </li>
<li class="fbimg"> <%= link_to("#{image_tag 'fb.png', size: '35x35'}".html_safe,user_omniauth_authorize_path(:facebook)) %> </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Freshman" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Freshman" %>">
    
    <%= render 'layouts/includes' %>
    <%= csrf_meta_tags %>
    
  </head>
  <body>
    <div id="wrap">

      <header>
        <%= render 'layouts/navigation' %>
      </header>

      <%= render 'layouts/messages' %>
      <%= yield %>
       
     </div>   
  </body>

  <%= render 'layouts/footer' %>

</html>

app/views/links/index.html.erb
<div class="space"></div>
<div class="container">
  <div class="row row-offcanvas row-offcanvas-right">
    <div class="col-xs-12 col-sm-9">
      <div class="row" id="contain">

        <% @links.each do |link| %>
        
          <div class="col-sm-6 col-md-4 grid">
            <div class="thumbnail">
              <font class="label <%= tag_setting(link.tag) %>">
                <%= link.tag %>
              </font>
              <br><%= link_to(image_tag(link.thumbnail, size: "120x120"), link.url, target: "_blank") %>
              <div class="caption">
                <h3><%= link_to(link.title, link.url, target: "_blank") %></h3>
                <p><%= link.content %></p>
                <p align="right">
                  <font color="#163F57"><strong>shared by Tony</strong></font>
                </p> 
              </div>
            </div>
          </div>
        
        <% end %>

      </div><!--/row-->
    </div><!--/span-->

    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">

      <%= link_to("Share A Link", new_link_path, class: "btn btn-primary") %>
      <hr>
      
      <div class="list-group">
        <%= link_to("All", links_path, class: "list-group-item active") %>
        
      </div>

      <div class="list-group">
        <%= link_to("Gem", links_path(tag: 'gem'), class: "list-group-item") %>
        <%= link_to("News", links_path(tag: 'news'), class: "list-group-item") %>
        <%= link_to("Teaching", links_path(tag: 'teach'), class: "list-group-item") %>
        <%= link_to("Discussion", links_path(tag: 'discuss'), class: "list-group-item") %>
      </div>
    </div><!--/span-->
  </div><!--/row-->
  
  <div class="text-center">
    <ul class="pagination center">
      <li>
        <a href="#">prev</a>
      </li>
      <li>
        <a href="#">1</a>
      </li>
      <li>
        <a href="#">2</a>
      </li>
      <li>
        <a href="#">3</a>
      </li>
      <li>
        <a href="#">4</a>
      </li>
      <li>
        <a href="#">5</a>
      </li>
      <li>
        <a href="#">next</a>
      </li>
    </ul>
  </div>
</div><!--/.container-->

<script type="text/javascript">

  $(document).ready(function() {
    var $container = $('#contain');
    // initialize Masonry after all images have loaded  
    $container.imagesLoaded( function() {
      $container.masonry({
        // options
        itemSelector: '.grid'
      });
    });
  }); 

</script>

app/views/links/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 box">
  	<h2 align="center">Share A Link</h2><hr>
    <%= simple_form_for @link do |f| %>
      <div class="form-group">
	      <%= f.input :url, label: "Link URL", required: true, autofocus: true, input_html: { :class => "form-control", id: "url" } %>
	    </div>

    <br><div class="selector-wrapper"></div><br>

	  <div class="form-group">
      <font size="3"><strong>Category</strong></font><br>
	    <%= f.collection_radio_buttons :tag, [['Gem', 'Gem'] ,['News', 'News'], ['Teaching', 'Teaching'], ['Discussion', 'Discussion']], :first, :last, required: true %>
	  </div>

	  <hr>
	  <div class="form-actions">
      <%= f.button :submit, "Share", class: "btn btn-primary btn-block" %>
  	</div>
    <% end %>
  </div>
</div>

<script>
  // Set up preview.
  $('#url').preview({key:'0cc898dfddd7445bb6761305d7ae7b5f'});

  $('form').on('submit', function(){
    $(this).addInputs($('#url').data('preview'));
    return true;
  });
</script>

app/views/welcome/index.html.erb
<div class="jumbotron big">
  <h1>Welcome to Rails Freshman</h1>
  <h3>
  	Learn Ruby on Rails by Sharing & Taking Down Notes, Thoughts and Links. 
  </h3>
    &nbsp
  <div class="row start-btn">
    <div class="col-md-2 col-md-offset-5">
      <%= link_to 'Starts Now', new_user_registration_path, :class => "btn btn-warning btn-lg" %>
    </div>
  </div>
</div>